// learn-vue/using-jsx/src/App.tsx
// import HelloWorld from './components/HelloWorld.vue'
// import HelloWorld from './components/HelloWorld.ts'
import HelloWorld from './components/HelloWorld.tsx'
// import { Hi } from './components/Hi.ts'
import { Hi } from './components/Hi.tsx'

export default function () {
  return (
    <>
      <HelloWorld message="hello world" />
      <Hi message="hihi">hahaha</Hi>
    </>
  )
}

// learn-vue/using-jsx/src/App.vue
<script setup lang="ts">
// import HelloWorld from './components/HelloWorld.vue'
// import HelloWorld from './components/HelloWorld.ts'
import HelloWorld from './components/HelloWorld.tsx'
// import { Hi } from './components/Hi.ts'
import { Hi } from './components/Hi.tsx'
</script>

<template>
  <HelloWorld message="hello world" />
  <Hi message="hihi">
    hahaha
  </Hi>
</template>
